#
#               Plugin: SpivakSpawners     |       Author: Plajer
#               Discord: Plajer#7013        | SpigotMC: https://www.spigotmc.org/members/423193/
#
#      Plugin Command: /spawners (/spawner, /ss) - Main plugin command
#      Permissions:
#       - spivakspawners.give - for '/ss give' command
#       - spivakspawners.givehead - for '/ss givehead' command
#       - spivakspawners.reload - for '/ss reload' command
#
#      Dependencies: Vault and any plugin that will handle Vault's economy

# Sound when player opens /heads GUI
# All list of valid sounds for 1.8 http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
Heads-Open-Sound: "LAVA_POP"

# Sound when player deposits heads into the /heads storage
Heads-Deposit-Sound: "NOTE_BASS_DRUM"

# Should we enable mobs merging feature?
Mob-Merge-Enabled: true

# Should we enable spawners merging feature?
# WARNING! Disabling this part of the plugin
# will disable all these features too:
# - Spawners Level GUI that shows spawner level on click
# - Spawners Mob Perks - no 10% more loot etc anymore
Spawners-Merge-Enabled: true