name: SpivakSpawners
author: Plajer
version: 1.0.0
main: pl.plajer.spivakspawners.Main
depend: [HolographicDisplays, Vault]

commands:
  spawners:
    aliases: [spawner, ss]
  heads:
    aliases: [head]